"Fixes #128"
1Shubham7/Wife-Predictor-v2 pull request #134
Opened 2024-10-01 16:08 UTC by NandaniThakur

added contributors in readme.md file.
I have added contributors just before Contributing.

2024-10-01 21:30 UTC, 1Shubham7 commented
hey @NandaniThakur, we actually want a list of images of those contributors . something like this :

![image](https://github.com/user-attachments/assets/bf943aec-8135-4962-a6e2-2b17e6589d1e)

please make changes accordingly : )

2024-10-01 21:30 UTC, 1Shubham7 requested changes
hey @NandaniThakur, we actually want a list of images of those contributors . something like this :

![image](https://github.com/user-attachments/assets/bf943aec-8135-4962-a6e2-2b17e6589d1e)

please make changes accordingly : )

2024-10-02 05:45 UTC, NandaniThakur commented
I have done the changes, please check it.

2024-10-02 05:53 UTC, 1Shubham7 requested changes
please also add a proper title to your PR

2025-06-07 06:34 UTC, closed without merging