Add 'Play Again' button to restart game after prediction
1Shubham7/Wife-Predictor-v2 pull request #151
Opened 2024-10-04 08:00 UTC by harish08102004

### What does this PR do?
This PR adds a "Play Again" button that allows users to restart the game without refreshing the page after a wife prediction has been made.

### Changes made:
- Added a "Play Again" button that becomes visible after a prediction is completed.
- When clicked, the button redirects the user back to the main page where they can enter a name and play again.
- Adjusted the logic to properly reset the game state, including unchecking the checkbox and resetting the input field.

### Why is this change required?
Previously, users had to refresh the page manually to play the game again. This addition streamlines the user experience by allowing them to easily start over with the new button.

### How to test:
1. Play the game by entering your name and checking the box.
2. After the wife prediction appears, click the "Play Again" button.
3. Verify that the game resets, allowing you to play again from the main page.

2024-10-04 08:01 UTC, harish08102004 commented
Hey @paulkrishanu4 please review and merge it.
Additionally please add labels.
hacktoberfest-accepted,
level

2024-10-07 11:45 UTC, 1Shubham7 requested changes
please share a video of how the play again works and looks after your changes : )

2024-10-07 11:47 UTC, harish08102004 commented
Ok I will do that.

2024-10-07 12:38 UTC, harish08102004 commented
Here is the screen recording of the changes made on implementing play again button.

https://github.com/user-attachments/assets/cf038ed6-4838-46c1-86fd-c702e19047ec

2024-10-07 12:53 UTC, 1Shubham7 approved these changes
looks good ! maybe the play again button can be improved. but we can do that in another PR : )

2024-10-07 12:53 UTC, merged

2024-10-07 12:56 UTC, harish08102004 commented
Hey @1Shubham7 can you add labels for this PR as same as Issue.

2024-10-07 12:57 UTC, 1Shubham7 commented
yes, was about to do that : )